name: BuildPython

on: 
  push:
    branches: [ master ]

jobs:
  prepare_assets:
    name: build a portable python for Mac
    runs-on: macos-latest
    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2

      - name: Run build script
        env:
          CMAKE_OSX_ARCHITECTURES: x86_64
        run: |
          sudo bash build.sh
          cp /Users/runner/Desktop/python_osx.zip ./python_osx.zip
          ls

      - name: Test if pip could install modules
        run: |
          sudo /Users/runner/Desktop/python/bin/python3 -m pip install pydantic
      

      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

