name: BuildPython

on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: build a portable python for Mac
    runs-on: macos-11
    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v4

      - name: Run build script
        env:
          CMAKE_OSX_ARCHITECTURES: x86_64
        run: |
          sudo bash build.sh 3.10.10 3.10
          mkdir assets
          cp /Users/runner/Desktop/MacPython.zip ./assets/MacPython.zip
          ls

      - name: zip python
        run: |
          echo "zip python"
          sudo cp -R /Users/runner/Desktop/python ./
          sudo zip -r python_osx.zip ./python
          cp ./python_osx.zip ./assets/python_osx.zip
          
          echo "unzip python test"
          mkdir newpython
          sudo unzip ./assets/python_osx.zip -d ./newpython
          cd newpython
          ls

      - name: Test python links
        run: |
          otool -l ./python/bin/python

      - name: Test if pip could install modules
        run: |
          sudo ./python/bin/python -m pip install pydantic
          sudo ./python/bin/python -m pip install ladybug-core
      
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          path: assets/*
      

  test:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3

      - name: unzip python zip
        run: |
          ls
          cp ./artifact/*.zip ./
          sudo unzip python_osx.zip
          ls
          cd ./python
          ls

      - name: Test if pip could install modules
        run: |
          sudo ./python/bin/python3 -m pip install ladybug-core

      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}



