name: BuildPython

on: 
  push:
    branches: [ master ]

jobs:
  prepare_assets:
    name: build a portable python for Mac
    runs-on: macos-11
    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v4

      - name: Check Homebrew- uninstall gettext
        run: |
          /usr/local/opt/gettext/bin/gettext --version
          brew list

          rm /usr/local/bin/gettext
          rm /usr/local/lib/libintl.8.dylib
          brew unlink gettext
          brew cleanup --prune=all
          
          brew uninstall --ignore-dependencies gettext

      - name: test gettext
        run: |
          /usr/local/opt/gettext/bin/gettext --version
          
      - name: Run build script
        env:
          CMAKE_OSX_ARCHITECTURES: x86_64
        run: |
          sudo bash build.sh 3.10.10 3.10
          cp /Users/runner/Desktop/python_osx.zip ./python_osx.zip
          ls

      - name: Test python links
        run: |
          otool -l /Users/runner/Desktop/python/bin/python

      - name: Test if pip could install modules
        run: |
          sudo /Users/runner/Desktop/python/bin/python -m pip install pydantic
      
      - name: Install gettext
        run: |
          brew install gettext

      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

