name: BuildPython

on: 
  push:
    branches: [ master ]

jobs:
  prepare_assets:
    name: build a portable python for Mac
    runs-on: macos-latest
    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v4

      - name: Check Homebrew- uninstall gettext
        run: |
          brew list
          brew uninstall --ignore-dependencies gettext

      - name: Run build script
        env:
          CMAKE_OSX_ARCHITECTURES: x86_64
        run: |
          sudo bash build379.sh 3.7.9 3.7
          cp /Users/runner/Desktop/python_osx.zip ./python_osx.zip
          ls

      - name: Test python links
        run: |
          otool -l /Users/runner/Desktop/python/bin/python
      
      - name: Test ssl lib's lik
        run: |
          otool -l /Users/runner/Desktop/python/lib/libssl.1.1.dylib

      - name: Test if pip could install modules
        run: |
          sudo /Users/runner/Desktop/python/bin/python -m pip install pydantic
      
      - name: Install gettext
        run: |
          brew install gettext

      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

