name: BuildPython

on: 
  push:
    branches: [ master ]

jobs:
  prepare_assets:
    name: build a portable python for Mac
    runs-on: macos-11
    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v4

      - name: Run build script
        env:
          CMAKE_OSX_ARCHITECTURES: x86_64
        run: |
          sudo bash build.sh 3.10.10 3.10
          cp /Users/runner/Desktop/python_osx.zip ./python_osx.zip
          ls

      - name: Test python links
        run: |
          otool -l /Users/runner/Desktop/python/bin/python

      - name: Test if pip could install modules
        run: |
          sudo cp -R /Users/runner/Desktop/python /Users/runner/Desktop/python2
          sudo /Users/runner/Desktop/python2/bin/python -m pip install pydantic
      
      - name: Upload installers
        uses: actions/upload-artifact@v3
        with:
          path: /Users/runner/Desktop/python
      
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

